# Reads the 4 standard Space Invaders arcade ROM files (invaders.h/g/f/e,
# 2KB each) from SI_ROM_DIR and writes a generated C source (SI_ROM_OUT)
# defining `space_invaders_rom` as an embedded byte array. Invoked via
# add_custom_command in CMakeLists.txt - not meant to be included directly.
#
# The ROM files aren't committed to this repo (see roms/README.md - it's
# Taito's copyrighted work, the user supplies their own dump). If one or
# more are missing, this generates zero-filled placeholder data for them
# instead of failing the build, so the rest of the project still compiles;
# a warning is printed either way so it's obvious the image won't actually
# run the real game.

set(SI_ROM_FILES
        "${SI_ROM_DIR}/invaders.h"
        "${SI_ROM_DIR}/invaders.g"
        "${SI_ROM_DIR}/invaders.f"
        "${SI_ROM_DIR}/invaders.e"
)

set(SI_ROM_HEX "")
set(SI_ROM_MISSING FALSE)

foreach(romfile ${SI_ROM_FILES})
    if(EXISTS "${romfile}")
        file(READ "${romfile}" filehex HEX)
        string(LENGTH "${filehex}" filehex_len)
        if(NOT filehex_len EQUAL 4096) # 2048 bytes == 4096 hex chars
            message(WARNING "generate_rom.cmake: ${romfile} is not exactly 2048 bytes (got ${filehex_len} hex chars / 2) - Space Invaders ROM files are always 2KB each. Continuing, but the embedded ROM image is likely wrong.")
        endif()
        string(APPEND SI_ROM_HEX "${filehex}")
    else()
        message(WARNING "generate_rom.cmake: missing ROM file ${romfile} (see roms/README.md) - substituting zero-filled placeholder data. The firmware will build but won't run the real game until this file is supplied.")
        string(REPEAT "00" 2048 zeros)
        string(APPEND SI_ROM_HEX "${zeros}")
        set(SI_ROM_MISSING TRUE)
    endif()
endforeach()

string(REGEX REPLACE "(..)" "0x\\1," SI_ROM_C_ARRAY "${SI_ROM_HEX}")

if(SI_ROM_MISSING)
    set(SI_ROM_COMMENT "// WARNING: one or more real ROM files were missing at build time - this\n// array contains zero-filled placeholder data in their place. See\n// roms/README.md, then re-run the build once the real dump is in place.")
else()
    set(SI_ROM_COMMENT "// Real Space Invaders arcade ROM, assembled from the 4 files in roms/.")
endif()

file(WRITE "${SI_ROM_OUT}" "// Auto-generated by cmake/generate_rom.cmake at build time - do not edit.
// Original Space Invaders arcade ROM (Taito/Midway, 1978), supplied
// locally by the user in roms/ - not vendored in this repository, see
// roms/README.md.
${SI_ROM_COMMENT}
#include <stdint.h>
#include <stddef.h>

const uint8_t space_invaders_rom[8192] = { ${SI_ROM_C_ARRAY} };
const size_t space_invaders_rom_size = 8192;
")
